- oml/lightning/modules/retrieval.py
Remove unnecessary v_num from logging.
> Remove unnecessary v_num from logging.

- README.md
- examples/cars/configs/train_cars.yaml
- examples/cars/configs/val_cars.yaml
- examples/cub/configs/train_cub.yaml
- examples/cub/configs/val_cub.yaml
- examples/inshop/configs/val_inshop.yaml
- oml/models/vit/vit.py
Added configs and weights for CUB 200 2011 and CARS 196 datasets
> Configs and weights for CUB 200 2011 and CARS 196 datasets

- oml/models/resnet.py
- oml/models/vit/vit.py
- tests/test_examples/test_runs_via_configs/configs/train_mock.yaml
- tests/test_oml/test_models/test_models_creation.py
made weights handling so it is now consistent with torchvision 0.13
> Refactored weights handling (consistency with torchvision model hub)

- oml/lightning/callbacks/metric.py
Improved error message about unpatched loaders
> Improved error message about unpatched loaders

- oml/lightning/entrypoints/train.py
> rm assert for loss interface

- docs/source/contents/datasets.rst
My bad, I've forgot to add ListDataset to documentation. Fixing it :)
> added list dataset documentation

- .github/workflows/pre-commit-workflow.yaml
Fix [this](https://github.com/actions/setup-python/issues/162#issuecomment-1325159952) pre-commit fail.
> Fix pre-commit fail

- oml/miners/inbatch_all_tri.py
- tests/test_oml/test_miners/test_inbatch_all_tri.py
`get_available_triplets` was rewritten in a loop-less manner by means of PyTorch and NumPy
> Improve implementation of get_available_triplets.

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
> Automatic publish to PyPI

- docs/source/contents/metrics.rst
- docs/source/contents/utils.rst
- examples/cars/configs/train_cars.yaml
- examples/cars/configs/val_cars.yaml
- examples/cub/configs/train_cub.yaml
- examples/cub/configs/val_cub.yaml
- examples/inshop/configs/train_inshop.yaml
- examples/inshop/configs/val_inshop.yaml
- examples/inshop/configs_experimental/train_inshop_arcface.yaml
- examples/inshop/configs_experimental/train_inshop_with_mlp.yaml
- examples/sop/configs/train_sop.yaml
- examples/sop/configs/val_sop.yaml
- oml/functional/metrics.py
- oml/metrics/embeddings.py
- oml/utils/misc.py
- oml/utils/misc_torch.py
- tests/test_oml/test_functional/test_metrics/test_topological_metrics.py
- tests/test_oml/test_metrics/test_embedding_metrics.py
- tests/test_oml/test_utils/test_misc_torch.py
Add calc_topological_metrics.
Add calc_main_components_percentage.
Add tests for new functions.
Fix old tests to work with new functions.
For now `calc_main_components_percentage` returns _percentage_ of main component, so if the original embeddings dim is 512, and this function returns 45, then the actual number of main components is $512\cdot 0.45$.
> Introduce topological metrics.

- examples/inshop/configs/val_inshop.yaml
- examples/sop/configs/val_sop.yaml
- oml/metrics/embeddings.py
and delete fmr_values in val_sop.yaml
For now, we don't push you to follow any predefined schema of issue, but ensure you've already read our contribution guide: https://open-metric-learning.readthedocs.io/en/latest/from_readme/contributing.html.
> turn off fmr default metric for embeddings.py

- README.md
- docs/readme/contributing.md
For now, we don't push you to follow any predefined schema of issue, but ensure you've already read our contribution guide: https://open-metric-learning.readthedocs.io/en/latest/from_readme/contributing.html.
> Edited Contributing Guide link in README

- oml/const.py
- oml/lightning/pipelines/parser.py
This PR adds W&B files logging (TODOs after previous PR https://github.com/OML-Team/open-metric-learning/pull/420)
> Wandb files logging

- oml/models/utils.py
- oml/models/vit_clip/extractor.py
> Model hot fix

- README.md
- docs/readme/documentation.md
For now, we don't push you to follow any predefined schema of issue, but ensure you've already read our contribution guide: https://open-metric-learning.readthedocs.io/en/latest/from_readme/contributing.html.
> Update link in docs for chinese article.

- README.md
- docs/readme/examples_source/extractor/train_val_img_txt.md
- docs/readme/examples_source/extractor/train_val_pl.md
- docs/readme/examples_source/extractor/train_val_pl_ddp.md
- docs/readme/library_features.md
- oml/lightning/__init__.py
- oml/metrics/__init__.py
Polished OML features and examples table
> Docs features

- .github/workflows/docker_tests.yaml
- .github/workflows/pre-commit-workflow.yaml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/tests.yaml
- oml/functional/metrics.py
- oml/metrics/embeddings.py
- pipelines/features_extraction/extractor_inshop/val_inshop.yaml
Misc:
* Fixed categories handling in pcf metric
* Added docs to calculating metrics by rr
* Added verbose argument
> Last changes for 3.0 release

- README.md
- docs/readme/faq.md
This PR introduces a new section to the FAQ addressing how to export models to ONNX.
> Add a new section to the FAQ

- README.md
- docs/readme/header.md
> Added yango tech logo

- .gitignore
- [*] I've checked contribution [guide](https://open-metric-learning.readthedocs.io/en/latest/oml/contributing.html).
> vscode data to gitignore

- README.md
- docs/readme/acknowledgments.md
- [ *] I've checked contribution [guide](https://open-metric-learning.readthedocs.io/en/latest/oml/contributing.html).
> Minor change in README

- oml/interfaces/models.py
- oml/models/meta/projection.py
> Added kwargs to `from_pretrained`

- ci/Dockerfile
- ci/requirements_audio.txt
Added necessary audio backends (`soundfile`) and extra index for `requirements_audio.txt` similar to `requirements.txt` in `Dockerfile`.
> Fix audio requirements

- oml/utils/misc.py
> Replace deprecated `tostring_rgb` to `buffer_rgba`

- README.md
- docs/readme/examples_source/extractor/train_val_img_txt.md
- docs/readme/examples_source/retrieval_format.md
- docs/readme/examples_source/zoo/models_usage.md
- docs/source/contents/datasets.rst
> Add audio docs

- README.md
- docs/readme/examples_source/extractor/train_val_all_modalities.md
- docs/readme/examples_source/retrieval_format.md
- docs/readme/examples_source/zoo/models_usage.md
- oml/datasets/texts.py
- oml/models/audio/ecapa_tdnn/extractor.py
- oml/models/utils.py
- oml/utils/misc.py
- tests/test_oml/test_utils/test_misc.py
- tests/test_runs/test_code_from_markdown.py
* Added audio train-val, zoo, dataset examples into tests
* Fixed text visualization when running as script
* Reworked ECAPA model to avoid problems with loading checkpoint from the disk (not from pretrained)
> Polishing recent audio contributions

- .github/workflows/tests.yaml
- Makefile
- README.md
- docs/readme/examples_source/zoo/zoo_audios.md
- docs/readme/examples_source/zoo/zoo_images.md
- docs/readme/examples_source/zoo/zoo_texts.md
- docs/readme/header.md
- docs/readme/installation.md
- docs/readme/library_features.md
- docs/source/contents/datasets.rst
- docs/source/contents/interfaces.rst
- docs/source/feature_extraction/zoo.rst
- oml/datasets/audios.py
- tests/test_runs/test_code_from_markdown.py
* Reworked docs: 3 separate zoo modules for every modality
* Updated .rst files by new functions and classes
* Added self-hosted neptune.ai logo
* Changed python version for all tests from 3.8 to 3.12
* Added python 3.12 to the testing grid
*
> Polishing after recent contributions 

- .github/workflows/tests.yaml
- ci/requirements.txt
- oml/configs/transforms/augs_albu.yaml
- oml/registry/transforms.py
- oml/transforms/images/albumentations.py
- oml/utils/misc.py
- pipelines/features_extraction/extractor_cars/train_cars.py
- pipelines/features_extraction/extractor_cub/train_cub.py
- tests/test_runs/test_pipelines/configs/train_arcface_with_categories.yaml
- tests/test_runs/test_pipelines/configs/train_with_categories.yaml
- tests/test_runs/test_pipelines/configs/train_with_sequence.yaml
> Adapt albu signatures for different versions

- .github/workflows/tests.yaml
- tests/test_runs/test_pipelines/configs/train_arcface_with_categories.yaml
- tests/test_runs/test_pipelines/configs/train_with_categories.yaml
- tests/test_runs/test_pipelines/configs/train_with_sequence.yaml
> Change wrong augs name for tests
